#pragma once
#ifndef _OSANDROID_KEYCODE_
#define _OSANDROID_KEYCODE_

static const int KEYCODE_UNKNOWN						= 0x00000000;	Key code constant: Unknown key code.
static const int KEYCODE_SOFT_LEFT						= 0x00000001;	Key code constant: Soft Left key. Usually situated below the display on phones and used as a multi-function feature key for selecting a software defined function shown on the bottom left of the display.
static const int KEYCODE_SOFT_RIGHT						= 0x00000002;	Key code constant: Soft Right key. Usually situated below the display on phones and used as a multi-function feature key for selecting a software defined function shown on the bottom right of the display.
static const int KEYCODE_HOME							= 0x00000003;	Key code constant: Home key. This key is handled by the framework and is never delivered to applications.
static const int KEYCODE_BACK							= 0x00000004;	Key code constant: Back key.
static const int KEYCODE_CALL							= 0x00000005;	Key code constant: Call key.
static const int KEYCODE_ENDCALL						= 0x00000006;	Key code constant: End Call key.
static const int KEYCODE_0								= 0x00000007;	Key code constant: '0' key.
static const int KEYCODE_1								= 0x00000008;	Key code constant: '1' key.
static const int KEYCODE_2								= 0x00000009;	Key code constant: '2' key.
static const int KEYCODE_3								= 0x0000000a;	Key code constant: '3' key.
static const int KEYCODE_4								= 0x0000000b;	Key code constant: '4' key.
static const int KEYCODE_5								= 0x0000000c;	Key code constant: '5' key.
static const int KEYCODE_6								= 0x0000000d;	Key code constant: '6' key.
static const int KEYCODE_7								= 0x0000000e;	Key code constant: '7' key.
static const int KEYCODE_8								= 0x0000000f;	Key code constant: '8' key.
static const int KEYCODE_9								= 0x00000010;	Key code constant: '9' key.
static const int KEYCODE_STAR							= 0x00000011;	Key code constant: '*' key.
static const int KEYCODE_POUND							= 0x00000012;	Key code constant: '#' key.
static const int KEYCODE_DPAD_UP						= 0x00000013;	Key code constant: Directional Pad Up key. May also be synthesized from trackball motions.
static const int KEYCODE_DPAD_DOWN						= 0x00000014;	Key code constant: Directional Pad Down key. May also be synthesized from trackball motions.
static const int KEYCODE_DPAD_LEFT						= 0x00000015;	Key code constant: Directional Pad Left key. May also be synthesized from trackball motions.
static const int KEYCODE_DPAD_RIGHT						= 0x00000016;	Key code constant: Directional Pad Right key. May also be synthesized from trackball motions.
static const int KEYCODE_DPAD_CENTER					= 0x00000017;	Key code constant: Directional Pad Center key. May also be synthesized from trackball motions.
static const int KEYCODE_VOLUME_UP						= 0x00000018;	Key code constant: Volume Up key. Adjusts the speaker volume up.
static const int KEYCODE_VOLUME_DOWN					= 0x00000019;	Key code constant: Volume Down key. Adjusts the speaker volume down.
static const int KEYCODE_POWER							= 0x0000001a;	Key code constant: Power key.
static const int KEYCODE_CAMERA							= 0x0000001b;	Key code constant: Camera key. Used to launch a camera application or take pictures.
static const int KEYCODE_CLEAR							= 0x0000001c;	Key code constant: Clear key.
static const int KEYCODE_A								= 0x0000001d;	Key code constant: 'A' key.
static const int KEYCODE_B								= 0x0000001e;	Key code constant: 'B' key.
static const int KEYCODE_C								= 0x0000001f;	Key code constant: 'C' key.
static const int KEYCODE_D								= 0x00000020;	Key code constant: 'D' key.
static const int KEYCODE_E								= 0x00000021;	Key code constant: 'E' key.
static const int KEYCODE_F								= 0x00000022;	Key code constant: 'F' key.
static const int KEYCODE_G								= 0x00000023;	Key code constant: 'G' key.
static const int KEYCODE_H								= 0x00000024;	Key code constant: 'H' key.
static const int KEYCODE_I								= 0x00000025;	Key code constant: 'I' key.
static const int KEYCODE_J								= 0x00000026;	Key code constant: 'J' key.
static const int KEYCODE_K								= 0x00000027;	Key code constant: 'K' key.
static const int KEYCODE_L								= 0x00000028;	Key code constant: 'L' key.
static const int KEYCODE_M								= 0x00000029;	Key code constant: 'M' key.
static const int KEYCODE_N								= 0x0000002a;	Key code constant: 'N' key.
static const int KEYCODE_O								= 0x0000002b;	Key code constant: 'O' key.
static const int KEYCODE_P								= 0x0000002c;	Key code constant: 'P' key.
static const int KEYCODE_Q								= 0x0000002d;	Key code constant: 'Q' key.
static const int KEYCODE_R								= 0x0000002e;	Key code constant: 'R' key.
static const int KEYCODE_S								= 0x0000002f;	Key code constant: 'S' key.
static const int KEYCODE_T								= 0x00000030;	Key code constant: 'T' key.
static const int KEYCODE_U								= 0x00000031;	Key code constant: 'U' key.
static const int KEYCODE_V								= 0x00000032;	Key code constant: 'V' key.
static const int KEYCODE_W								= 0x00000033;	Key code constant: 'W' key.
static const int KEYCODE_X								= 0x00000034;	Key code constant: 'X' key.
static const int KEYCODE_Y								= 0x00000035;	Key code constant: 'Y' key.
static const int KEYCODE_Z								= 0x00000036;	Key code constant: 'Z' key.
static const int KEYCODE_COMMA							= 0x00000037;	Key code constant: ',' key.
static const int KEYCODE_PERIOD							= 0x00000038;	Key code constant: '.' key.
static const int KEYCODE_ALT_LEFT						= 0x00000039;	Key code constant: Left Alt modifier key.
static const int KEYCODE_ALT_RIGHT						= 0x0000003a;	Key code constant: Right Alt modifier key.
static const int KEYCODE_SHIFT_LEFT						= 0x0000003b;	Key code constant: Left Shift modifier key.
static const int KEYCODE_SHIFT_RIGHT					= 0x0000003c;	Key code constant: Right Shift modifier key.
static const int KEYCODE_TAB							= 0x0000003d;	Key code constant: Tab key.
static const int KEYCODE_SPACE							= 0x0000003e;	Key code constant: Space key.
static const int KEYCODE_SYM							= 0x0000003f;	Key code constant: Symbol modifier key. Used to enter alternate symbols.
static const int KEYCODE_EXPLORER						= 0x00000040;	Key code constant: Explorer special function key. Used to launch a browser application.
static const int KEYCODE_ENVELOPE						= 0x00000041;	Key code constant: Envelope special function key. Used to launch a mail application.
static const int KEYCODE_ENTER							= 0x00000042;	Key code constant: Enter key.
static const int KEYCODE_DEL							= 0x00000043;	Key code constant: Backspace key. Deletes characters before the insertion point, unlike KEYCODE_FORWARD_DEL.
static const int KEYCODE_GRAVE							= 0x00000044;	Key code constant: '`' (backtick) key.
static const int KEYCODE_MINUS							= 0x00000045;	Key code constant: '-'.
static const int KEYCODE_EQUALS							= 0x00000046;	Key code constant: '=' key.
static const int KEYCODE_LEFT_BRACKET					= 0x00000047;	Key code constant: '[' key.
static const int KEYCODE_RIGHT_BRACKET					= 0x00000048;	Key code constant: ']' key.
static const int KEYCODE_BACKSLASH						= 0x00000049;	Key code constant: '\' key.
static const int KEYCODE_SEMICOLON						= 0x0000004a;	Key code constant: ';' key.
static const int KEYCODE_APOSTROPHE						= 0x0000004b;	Key code constant: ''' (apostrophe) key.
static const int KEYCODE_SLASH							= 0x0000004c;	Key code constant: '/' key.
static const int KEYCODE_AT								= 0x0000004d;	Key code constant: '@' key.
static const int KEYCODE_NUM							= 0x0000004e;	Key code constant: Number modifier key. Used to enter numeric symbols. This key is not Num Lock; it is more like KEYCODE_ALT_LEFT and is interpreted as an ALT key by MetaKeyKeyListener.
static const int KEYCODE_HEADSETHOOK					= 0x0000004f;	Key code constant: Headset Hook key. Used to hang up calls and stop media.
static const int KEYCODE_FOCUS							= 0x00000050;	Key code constant: Camera Focus key. Used to focus the camera.
static const int KEYCODE_PLUS							= 0x00000051;	Key code constant: '+' key.
static const int KEYCODE_MENU							= 0x00000052;	Key code constant: Menu key.
static const int KEYCODE_NOTIFICATION					= 0x00000053;	Key code constant: Notification key.
static const int KEYCODE_SEARCH							= 0x00000054;	Key code constant: Search key.
static const int KEYCODE_MEDIA_PLAY_PAUSE				= 0x00000055;	Key code constant: Play/Pause media key.
static const int KEYCODE_MEDIA_STOP						= 0x00000056;	Key code constant: Stop media key.
static const int KEYCODE_MEDIA_NEXT						= 0x00000057;	Key code constant: Play Next media key.
static const int KEYCODE_MEDIA_PREVIOUS					= 0x00000058;	Key code constant: Play Previous media key.
static const int KEYCODE_MEDIA_REWIND					= 0x00000059;	Key code constant: Rewind media key.
static const int KEYCODE_MEDIA_FAST_FORWARD				= 0x0000005a;	Key code constant: Fast Forward media key.
static const int KEYCODE_MUTE							= 0x0000005b;	Key code constant: Mute key. Mutes the microphone, unlike KEYCODE_VOLUME_MUTE.
static const int KEYCODE_PAGE_UP						= 0x0000005c;	Key code constant: Page Up key.
static const int KEYCODE_PAGE_DOWN						= 0x0000005d;	Key code constant: Page Down key.
static const int KEYCODE_PICTSYMBOLS					= 0x0000005e;	Key code constant: Picture Symbols modifier key. Used to switch symbol sets (Emoji, Kao-moji).
static const int KEYCODE_SWITCH_CHARSET					= 0x0000005f;	Key code constant: Switch Charset modifier key. Used to switch character sets (Kanji, Katakana).
static const int KEYCODE_BUTTON_A						= 0x00000060;	Key code constant: A Button key. On a game controller, the A button should be either the button labeled A or the first button on the bottom row of controller buttons.
static const int KEYCODE_BUTTON_B						= 0x00000061;	Key code constant: B Button key. On a game controller, the B button should be either the button labeled B or the second button on the bottom row of controller buttons.
static const int KEYCODE_BUTTON_C						= 0x00000062;	Key code constant: C Button key. On a game controller, the C button should be either the button labeled C or the third button on the bottom row of controller buttons.
static const int KEYCODE_BUTTON_X						= 0x00000063;	Key code constant: X Button key. On a game controller, the X button should be either the button labeled X or the first button on the upper row of controller buttons.
static const int KEYCODE_BUTTON_Y						= 0x00000064;	Key code constant: Y Button key. On a game controller, the Y button should be either the button labeled Y or the second button on the upper row of controller buttons.
static const int KEYCODE_BUTTON_Z						= 0x00000065;	Key code constant: Z Button key. On a game controller, the Z button should be either the button labeled Z or the third button on the upper row of controller buttons.
static const int KEYCODE_BUTTON_L1						= 0x00000066;	Key code constant: L1 Button key. On a game controller, the L1 button should be either the button labeled L1 (or L) or the top left trigger button.
static const int KEYCODE_BUTTON_R1						= 0x00000067;	Key code constant: R1 Button key. On a game controller, the R1 button should be either the button labeled R1 (or R) or the top right trigger button.
static const int KEYCODE_BUTTON_L2						= 0x00000068;	Key code constant: L2 Button key. On a game controller, the L2 button should be either the button labeled L2 or the bottom left trigger button.
static const int KEYCODE_BUTTON_R2						= 0x00000069;	Key code constant: R2 Button key. On a game controller, the R2 button should be either the button labeled R2 or the bottom right trigger button.
static const int KEYCODE_BUTTON_THUMBL					= 0x0000006a;	Key code constant: Left Thumb Button key. On a game controller, the left thumb button indicates that the left (or only) joystick is pressed.
static const int KEYCODE_BUTTON_THUMBR					= 0x0000006b;	Key code constant: Right Thumb Button key. On a game controller, the right thumb button indicates that the right joystick is pressed.
static const int KEYCODE_BUTTON_START					= 0x0000006c;	Key code constant: Start Button key. On a game controller, the button labeled Start.
static const int KEYCODE_BUTTON_SELECT					= 0x0000006d;	Key code constant: Select Button key. On a game controller, the button labeled Select.
static const int KEYCODE_BUTTON_MODE					= 0x0000006e;	Key code constant: Mode Button key. On a game controller, the button labeled Mode.
static const int KEYCODE_ESCAPE							= 0x0000006f;	Key code constant: Escape key.
static const int KEYCODE_FORWARD_DEL					= 0x00000070;	Key code constant: Forward Delete key. Deletes characters ahead of the insertion point, unlike KEYCODE_DEL.
static const int KEYCODE_CTRL_LEFT						= 0x00000071;	Key code constant: Left Control modifier key.
static const int KEYCODE_CTRL_RIGHT						= 0x00000072;	Key code constant: Right Control modifier key.
static const int KEYCODE_CAPS_LOCK						= 0x00000073;	Key code constant: Caps Lock key.
static const int KEYCODE_SCROLL_LOCK					= 0x00000074;	Key code constant: Scroll Lock key.
static const int KEYCODE_META_LEFT						= 0x00000075;	Key code constant: Left Meta modifier key.
static const int KEYCODE_META_RIGHT						= 0x00000076;	Key code constant: Right Meta modifier key.
static const int KEYCODE_FUNCTION						= 0x00000077;	Key code constant: Function modifier key.
static const int KEYCODE_SYSRQ							= 0x00000078;	Key code constant: System Request / Print Screen key.
static const int KEYCODE_BREAK							= 0x00000079;	Key code constant: Break / Pause key.
static const int KEYCODE_MOVE_HOME						= 0x0000007a;	Key code constant: Home Movement key. Used for scrolling or moving the cursor around to the start of a line or to the top of a list.
static const int KEYCODE_MOVE_END						= 0x0000007b;	Key code constant: End Movement key. Used for scrolling or moving the cursor around to the end of a line or to the bottom of a list.
static const int KEYCODE_INSERT							= 0x0000007c;	Key code constant: Insert key. Toggles insert / overwrite edit mode.
static const int KEYCODE_FORWARD						= 0x0000007d;	Key code constant: Forward key. Navigates forward in the history stack. Complement of KEYCODE_BACK.
static const int KEYCODE_MEDIA_PLAY						= 0x0000007e;	Key code constant: Play media key.
static const int KEYCODE_MEDIA_PAUSE					= 0x0000007f;	Key code constant: Pause media key.
static const int KEYCODE_MEDIA_CLOSE					= 0x00000080;	Key code constant: Close media key. May be used to close a CD tray, for example.
static const int KEYCODE_MEDIA_EJECT					= 0x00000081;	Key code constant: Eject media key. May be used to eject a CD tray, for example.
static const int KEYCODE_MEDIA_RECORD					= 0x00000082;	Key code constant: Record media key.
static const int KEYCODE_F1								= 0x00000083;	Key code constant: F1 key.
static const int KEYCODE_F2								= 0x00000084;	Key code constant: F2 key.
static const int KEYCODE_F3								= 0x00000085;	Key code constant: F3 key.
static const int KEYCODE_F4								= 0x00000086;	Key code constant: F4 key.
static const int KEYCODE_F5								= 0x00000087;	Key code constant: F5 key.
static const int KEYCODE_F6								= 0x00000088;	Key code constant: F6 key.
static const int KEYCODE_F7								= 0x00000089;	Key code constant: F7 key.
static const int KEYCODE_F8								= 0x0000008a;	Key code constant: F8 key.
static const int KEYCODE_F9								= 0x0000008b;	Key code constant: F9 key.
static const int KEYCODE_F10							= 0x0000008c;	Key code constant: F10 key.
static const int KEYCODE_F11							= 0x0000008d;	Key code constant: F11 key.
static const int KEYCODE_F12							= 0x0000008e;	Key code constant: F12 key.
static const int KEYCODE_NUM_LOCK						= 0x0000008f;	Key code constant: Num Lock key. This is the Num Lock key; it is different from KEYCODE_NUM. This key alters the behavior of other keys on the numeric keypad.
static const int KEYCODE_NUMPAD_0						= 0x00000090;	Key code constant: Numeric keypad '0' key.
static const int KEYCODE_NUMPAD_1						= 0x00000091;	Key code constant: Numeric keypad '1' key.
static const int KEYCODE_NUMPAD_2						= 0x00000092;	Key code constant: Numeric keypad '2' key.
static const int KEYCODE_NUMPAD_3						= 0x00000093;	Key code constant: Numeric keypad '3' key.
static const int KEYCODE_NUMPAD_4						= 0x00000094;	Key code constant: Numeric keypad '4' key.
static const int KEYCODE_NUMPAD_5						= 0x00000095;	Key code constant: Numeric keypad '5' key.
static const int KEYCODE_NUMPAD_6						= 0x00000096;	Key code constant: Numeric keypad '6' key.
static const int KEYCODE_NUMPAD_7						= 0x00000097;	Key code constant: Numeric keypad '7' key.
static const int KEYCODE_NUMPAD_8						= 0x00000098;	Key code constant: Numeric keypad '8' key.
static const int KEYCODE_NUMPAD_9						= 0x00000099;	Key code constant: Numeric keypad '9' key.
static const int KEYCODE_NUMPAD_DIVIDE					= 0x0000009a;	Key code constant: Numeric keypad '/' key (for division).
static const int KEYCODE_NUMPAD_MULTIPLY				= 0x0000009b;	Key code constant: Numeric keypad '*' key (for multiplication).
static const int KEYCODE_NUMPAD_SUBTRACT				= 0x0000009c;	Key code constant: Numeric keypad '-' key (for subtraction).
static const int KEYCODE_NUMPAD_ADD						= 0x0000009d;	Key code constant: Numeric keypad '+' key (for addition).
static const int KEYCODE_NUMPAD_DOT						= 0x0000009e;	Key code constant: Numeric keypad '.' key (for decimals or digit grouping).
static const int KEYCODE_NUMPAD_COMMA					= 0x0000009f;	Key code constant: Numeric keypad ',' key (for decimals or digit grouping).
static const int KEYCODE_NUMPAD_ENTER					= 0x000000a0;	Key code constant: Numeric keypad Enter key.
static const int KEYCODE_NUMPAD_EQUALS					= 0x000000a1;	Key code constant: Numeric keypad '=' key.
static const int KEYCODE_NUMPAD_LEFT_PAREN				= 0x000000a2;	Key code constant: Numeric keypad '(' key.
static const int KEYCODE_NUMPAD_RIGHT_PAREN				= 0x000000a3;	Key code constant: Numeric keypad ')' key.
static const int KEYCODE_VOLUME_MUTE					= 0x000000a4;	Key code constant: Volume Mute key. Mutes the speaker, unlike KEYCODE_MUTE. This key should normally be implemented as a toggle such that the first press mutes the speaker and the second press restores the original volume.
static const int KEYCODE_INFO							= 0x000000a5;	Key code constant: Info key. Common on TV remotes to show additional information related to what is currently being viewed.
static const int KEYCODE_CHANNEL_UP						= 0x000000a6;	Key code constant: Channel up key. On TV remotes, increments the television channel.
static const int KEYCODE_CHANNEL_DOWN					= 0x000000a7;	Key code constant: Channel down key. On TV remotes, decrements the television channel.
static const int KEYCODE_ZOOM_IN						= 0x000000a8;	Key code constant: Zoom in key.
static const int KEYCODE_ZOOM_OUT						= 0x000000a9;	Key code constant: Zoom out key.
static const int KEYCODE_TV								= 0x000000aa;	Key code constant: TV key. On TV remotes, switches to viewing live TV.
static const int KEYCODE_WINDOW							= 0x000000ab;	Key code constant: Window key. On TV remotes, toggles picture-in-picture mode or other windowing functions. On Android Wear devices, triggers a display offset.
static const int KEYCODE_GUIDE							= 0x000000ac;	Key code constant: Guide key. On TV remotes, shows a programming guide.
static const int KEYCODE_DVR							= 0x000000ad;	Key code constant: DVR key. On some TV remotes, switches to a DVR mode for recorded shows.
static const int KEYCODE_BOOKMARK						= 0x000000ae;	Key code constant: Bookmark key. On some TV remotes, bookmarks content or web pages.
static const int KEYCODE_CAPTIONS						= 0x000000af;	Key code constant: Toggle captions key. Switches the mode for closed-captioning text, for example during television shows.
static const int KEYCODE_SETTINGS						= 0x000000b0;	Key code constant: Settings key. Starts the system settings activity.
static const int KEYCODE_TV_POWER						= 0x000000b1;	Key code constant: TV power key. On TV remotes, toggles the power on a television screen.
static const int KEYCODE_TV_INPUT						= 0x000000b2;	Key code constant: TV input key. On TV remotes, switches the input on a television screen.
static const int KEYCODE_STB_POWER						= 0x000000b3;	Key code constant: Set-top-box power key. On TV remotes, toggles the power on an external Set-top-box.
static const int KEYCODE_STB_INPUT						= 0x000000b4;	Key code constant: Set-top-box input key. On TV remotes, switches the input mode on an external Set-top-box.
static const int KEYCODE_AVR_POWER						= 0x000000b5;	Key code constant: A/V Receiver power key. On TV remotes, toggles the power on an external A/V Receiver.
static const int KEYCODE_AVR_INPUT						= 0x000000b6;	Key code constant: A/V Receiver input key. On TV remotes, switches the input mode on an external A/V Receiver.
static const int KEYCODE_PROG_RED						= 0x000000b7;	Key code constant: Red "programmable" key. On TV remotes, acts as a contextual/programmable key.
static const int KEYCODE_PROG_GREEN						= 0x000000b8;	Key code constant: Green "programmable" key. On TV remotes, actsas a contextual/programmable key.
static const int KEYCODE_PROG_YELLOW					= 0x000000b9;	Key code constant: Yellow "programmable" key. On TV remotes, acts as a contextual/programmable key.
static const int KEYCODE_PROG_BLUE						= 0x000000ba;	Key code constant: Blue "programmable" key. On TV remotes, acts as a contextual/programmable key.
static const int KEYCODE_APP_SWITCH						= 0x000000bb;	Key code constant: App switch key. Should bring up the application switcher dialog.
static const int KEYCODE_BUTTON_1						= 0x000000bc;	Key code constant: Generic Game Pad Button #1.
static const int KEYCODE_BUTTON_2						= 0x000000bd;	Key code constant: Generic Game Pad Button #2.
static const int KEYCODE_BUTTON_3						= 0x000000be;	Key code constant: Generic Game Pad Button #3.
static const int KEYCODE_BUTTON_4						= 0x000000bf;	Key code constant: Generic Game Pad Button #4.
static const int KEYCODE_BUTTON_5						= 0x000000c0;	Key code constant: Generic Game Pad Button #5.
static const int KEYCODE_BUTTON_6						= 0x000000c1;	Key code constant: Generic Game Pad Button #6.
static const int KEYCODE_BUTTON_7						= 0x000000c2;	Key code constant: Generic Game Pad Button #7.
static const int KEYCODE_BUTTON_8						= 0x000000c3;	Key code constant: Generic Game Pad Button #8.
static const int KEYCODE_BUTTON_9						= 0x000000c4;	Key code constant: Generic Game Pad Button #9.
static const int KEYCODE_BUTTON_10						= 0x000000c5;	Key code constant: Generic Game Pad Button #10.
static const int KEYCODE_BUTTON_11						= 0x000000c6;	Key code constant: Generic Game Pad Button #11.
static const int KEYCODE_BUTTON_12						= 0x000000c7;	Key code constant: Generic Game Pad Button #12.
static const int KEYCODE_BUTTON_13						= 0x000000c8;	Key code constant: Generic Game Pad Button #13.
static const int KEYCODE_BUTTON_14						= 0x000000c9;	Key code constant: Generic Game Pad Button #14.
static const int KEYCODE_BUTTON_15						= 0x000000ca;	Key code constant: Generic Game Pad Button #15.
static const int KEYCODE_BUTTON_16						= 0x000000cb;	Key code constant: Generic Game Pad Button #16.
static const int KEYCODE_LANGUAGE_SWITCH				= 0x000000cc;	Key code constant: Language Switch key. Toggles the current input language such as switching between English and Japanese on a QWERTY keyboard. On some devices, the same function may be performed by pressing Shift+Spacebar.
static const int KEYCODE_MANNER_MODE					= 0x000000cd;	Key code constant: Manner Mode key. Toggles silent or vibrate mode on and off to make the device behave more politely in certain settings such as on a crowded train. On some devices, the key may only operate when long-pressed.
static const int KEYCODE_3D_MODE						= 0x000000ce;	3D Mode key. Toggles the display between 2D and 3D mode.
static const int KEYCODE_CONTACTS						= 0x000000cf;	Key code constant: Contacts special function key. Used to launch an address book application.
static const int KEYCODE_CALENDAR						= 0x000000d0;	Key code constant: Calendar special function key. Used to launch a calendar application.
static const int KEYCODE_MUSIC							= 0x000000d1;	Key code constant: Music special function key. Used to launch a music player application.
static const int KEYCODE_CALCULATOR						= 0x000000d2;	Key code constant: Calculator special function key. Used to launch a calculator application.
static const int KEYCODE_ZENKAKU_HANKAKU				= 0x000000d3;	Key code constant: Japanese full-width / half-width key.
static const int KEYCODE_EISU							= 0x000000d4;	Key code constant: Japanese alphanumeric key.
static const int KEYCODE_MUHENKAN						= 0x000000d5;	Key code constant: Japanese non-conversion key.
static const int KEYCODE_HENKAN							= 0x000000d6;	Key code constant: Japanese conversion key.
static const int KEYCODE_KATAKANA_HIRAGANA				= 0x000000d7;	Key code constant: Japanese katakana / hiragana key.
static const int KEYCODE_YEN							= 0x000000d8;	Key code constant: Japanese Yen key.
static const int KEYCODE_RO								= 0x000000d9;	Key code constant: Japanese Ro key.
static const int KEYCODE_KANA							= 0x000000da;	Key code constant: Japanese kana key.
static const int KEYCODE_ASSIST							= 0x000000db;	Key code constant: Assist key. Launches the global assist activity. Not delivered to applications.
static const int KEYCODE_BRIGHTNESS_DOWN				= 0x000000dc;	Key code constant: Brightness Down key. Adjusts the screen brightness down.
static const int KEYCODE_BRIGHTNESS_UP					= 0x000000dd;	Key code constant: Brightness Up key. Adjusts the screen brightness up.
static const int KEYCODE_MEDIA_AUDIO_TRACK				= 0x000000de;	Key code constant: Audio Track key. Switches the audio tracks.
static const int KEYCODE_SLEEP							= 0x000000df;	Key code constant: Sleep key. Puts the device to sleep. Behaves somewhat like KEYCODE_POWER but it has no effect if the device is already asleep.
static const int KEYCODE_WAKEUP							= 0x000000e0;	Key code constant: Wakeup key. Wakes up the device. Behaves somewhat like KEYCODE_POWER but it has no effect if the device is already awake.
static const int KEYCODE_PAIRING						= 0x000000e1;	Key code constant: Pairing key. Initiates peripheral pairing mode. Useful for pairing remote control devices or game controllers, especially if no other input mode is available.
static const int KEYCODE_MEDIA_TOP_MENU					= 0x000000e2;	Key code constant: Media Top Menu key. Goes to the top of media menu.
static const int KEYCODE_11								= 0x000000e3;	Key code constant: '11' key.
static const int KEYCODE_12								= 0x000000e4;	Key code constant: '12' key.
static const int KEYCODE_LAST_CHANNEL					= 0x000000e5;	Key code constant: Last Channel key. Goes to the last viewed channel.
static const int KEYCODE_TV_DATA_SERVICE				= 0x000000e6;	Key code constant: TV data service key. Displays data services like weather, sports.
static const int KEYCODE_VOICE_ASSIST					= 0x000000e7;	Key code constant: Voice Assist key. Launches the global voice assist activity. Not delivered to applications.
static const int KEYCODE_TV_RADIO_SERVICE				= 0x000000e8;	Key code constant: Radio key. Toggles TV service / Radio service.
static const int KEYCODE_TV_TELETEXT					= 0x000000e9;	Key code constant: Teletext key. Displays Teletext service.
static const int KEYCODE_TV_NUMBER_ENTRY				= 0x000000ea;	Key code constant: Number entry key. Initiates to enter multi-digit channel nubmber when each digit key is assigned for selecting separate channel. Corresponds to Number Entry Mode (0x1D) of CEC User Control Code.
static const int KEYCODE_TV_TERRESTRIAL_ANALOG			= 0x000000eb;	Key code constant: Analog Terrestrial key. Switches to analog terrestrial broadcast service.
static const int KEYCODE_TV_TERRESTRIAL_DIGITAL			= 0x000000ec;	Key code constant: Digital Terrestrial key. Switches to digital terrestrial broadcast service.
static const int KEYCODE_TV_SATELLITE					= 0x000000ed;	Key code constant: Satellite key. Switches to digital satellite broadcast service.
static const int KEYCODE_TV_SATELLITE_BS				= 0x000000ee;	Key code constant: BS key. Switches to BS digital satellite broadcasting service available in Japan.
static const int KEYCODE_TV_SATELLITE_CS				= 0x000000ef;	Key code constant: CS key. Switches to CS digital satellite broadcasting service available in Japan.
static const int KEYCODE_TV_SATELLITE_SERVICE			= 0x000000f0;	Key code constant: BS/CS key. Toggles between BS and CS digital satellite services.
static const int KEYCODE_TV_NETWORK						= 0x000000f1;	Key code constant: Toggle Network key. Toggles selecting broacast services.
static const int KEYCODE_TV_ANTENNA_CABLE				= 0x000000f2;	Key code constant: Antenna/Cable key. Toggles broadcast input source between antenna and cable.
static const int KEYCODE_TV_INPUT_HDMI_1				= 0x000000f3;	Key code constant: HDMI #1 key. Switches to HDMI input #1.
static const int KEYCODE_TV_INPUT_HDMI_2				= 0x000000f4;	Key code constant: HDMI #2 key. Switches to HDMI input #2.
static const int KEYCODE_TV_INPUT_HDMI_3				= 0x000000f5;	Key code constant: HDMI #3 key. Switches to HDMI input #3.
static const int KEYCODE_TV_INPUT_HDMI_4				= 0x000000f6;	Key code constant: HDMI #4 key. Switches to HDMI input #4.
static const int KEYCODE_TV_INPUT_COMPOSITE_1			= 0x000000f7;	Key code constant: Composite #1 key. Switches to composite video input #1.
static const int KEYCODE_TV_INPUT_COMPOSITE_2			= 0x000000f8;	Key code constant: Composite #2 key. Switches to composite video input #2.
static const int KEYCODE_TV_INPUT_COMPONENT_1			= 0x000000f9;	Key code constant: Component #1 key. Switches to component video input #1.
static const int KEYCODE_TV_INPUT_COMPONENT_2			= 0x000000fa;	Key code constant: Component #2 key. Switches to component video input #2.
static const int KEYCODE_TV_INPUT_VGA_1					= 0x000000fb;	Key code constant: VGA #1 key. Switches to VGA (analog RGB) input #1.
static const int KEYCODE_TV_AUDIO_DESCRIPTION			= 0x000000fc;	Key code constant: Audio description key. Toggles audio description off / on.
static const int KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP	= 0x000000fd;	Key code constant: Audio description mixing volume up key. Louden audio description volume as compared with normal audio volume.
static const int KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN	= 0x000000fe;	Key code constant: Audio description mixing volume down key. Lessen audio description volume as compared with normal audio volume.
static const int KEYCODE_TV_ZOOM_MODE					= 0x000000ff;	Key code constant: Zoom mode key. Changes Zoom mode (Normal, Full, Zoom, Wide-zoom, etc.)
static const int KEYCODE_TV_CONTENTS_MENU				= 0x00000100;	Key code constant: Contents menu key. Goes to the title list. Corresponds to Contents Menu (0x0B) of CEC User Control Code
static const int KEYCODE_TV_MEDIA_CONTEXT_MENU			= 0x00000101;	Key code constant: Media context menu key. Goes to the context menu of media contents. Corresponds to Media Context-sensitive Menu (0x11) of CEC User Control Code.
static const int KEYCODE_TV_TIMER_PROGRAMMING			= 0x00000102;	Key code constant: Timer programming key. Goes to the timer recording menu. Corresponds to Timer Programming (0x54) of CEC User Control Code.
static const int KEYCODE_HELP							= 0x00000103;	Key code constant: Help key.
static const int KEYCODE_NAVIGATE_PREVIOUS				= 0x00000104;	Key code constant: Navigate to previous key. Goes backward by one item in an ordered collection of items.
static const int KEYCODE_NAVIGATE_NEXT					= 0x00000105;	Key code constant: Navigate to next key. Advances to the next item in an ordered collection of items.
static const int KEYCODE_NAVIGATE_IN					= 0x00000106;	Key code constant: Navigate in key. Activates the item that currently has focus or expands to the next level of a navigation hierarchy.
static const int KEYCODE_NAVIGATE_OUT					= 0x00000107;	Key code constant: Navigate out key. Backs out one level of a navigation hierarchy or collapses the item that currently has focus.
static const int KEYCODE_STEM_PRIMARY					= 0x00000108;	Key code constant: Primary stem key for Wear Main power/reset button on watch.
static const int KEYCODE_STEM_1							= 0x00000109;	Key code constant: Generic stem key 1 for Wear
static const int KEYCODE_STEM_2							= 0x0000010a;	Key code constant: Generic stem key 2 for Wear
static const int KEYCODE_STEM_3							= 0x0000010b;	Key code constant: Generic stem key 3 for Wear
static const int KEYCODE_DPAD_UP_LEFT					= 0x0000010c;	Key code constant: Directional Pad Up-Left
static const int KEYCODE_DPAD_DOWN_LEFT					= 0x0000010d;	Key code constant: Directional Pad Down-Left
static const int KEYCODE_DPAD_UP_RIGHT					= 0x0000010e;	Key code constant: Directional Pad Up-Right
static const int KEYCODE_DPAD_DOWN_RIGHT				= 0x0000010f;	Key code constant: Directional Pad Down-Right
static const int KEYCODE_MEDIA_SKIP_FORWARD				= 0x00000110;	Key code constant: Skip forward media key.
static const int KEYCODE_MEDIA_SKIP_BACKWARD			= 0x00000111;	Key code constant: Skip backward media key.
static const int KEYCODE_MEDIA_STEP_FORWARD				= 0x00000112;	Key code constant: Step forward media key. Steps media forward, one frame at a time.
static const int KEYCODE_MEDIA_STEP_BACKWARD			= 0x00000113;	Key code constant: Step backward media key. Steps media backward, one frame at a time.
static const int KEYCODE_SOFT_SLEEP						= 0x00000114;	Key code constant: put device to sleep unless a wakelock is held.
static const int KEYCODE_CUT							= 0x00000115;	Key code constant: Cut key.
static const int KEYCODE_COPY							= 0x00000116;	Key code constant: Copy key.
static const int KEYCODE_PASTE							= 0x00000117;	Key code constant: Paste key.
static const int KEYCODE_SYSTEM_NAVIGATION_UP			= 0x00000118;	Key code constant: Consumed by the system for navigation up
static const int KEYCODE_SYSTEM_NAVIGATION_DOWN			= 0x00000119;	Key code constant: Consumed by the system for navigation down
static const int KEYCODE_SYSTEM_NAVIGATION_LEFT			= 0x0000011a;	Key code constant: Consumed by the system for navigation left
static const int KEYCODE_SYSTEM_NAVIGATION_RIGHT		= 0x0000011b;	Key code constant: Consumed by the system for navigation right

#endif // _OSANDROID_KEYCODE_
